version: '3.3'
services:
        database:
                image: almuhs/gamedb:v1
                container_name: mariagame
                hostname: mariagame
                read_only: false
                volumes:
                        - gamedb-vol:/var/lib/mysql
                networks:
                        - mynet
        redis:
                image: redis
                container_name: redis
                volumes:
                        - redis-vol:/data
                networks:
                        - mynet
        webapp:
                image: almuhs/gameapp:v2
                container_name: webgame
                ports:
                        - "127.0.0.1:8080:80"
                environment:
                        - MYSQL_HOST=mariagame
                networks:
                        - mynet
                depends_on:
                        - database
                        - redis           
        ranking:
                image: almuhs/gameranking:v1
                container_name: ranking
                environment:
                        - MYSQL_HOST=mariagame
                ports:
                        - "127.0.0.1:8081:80"
                volumes:
                        - gamedb-vol:/var/lib/mysql
                networks:
                        - mynet
                depends_on:
                        - database
                        - webapp
volumes:
        gamedb-vol:
                external: false
        
        redis-vol:
                external: false
networks:
        mynet:
                driver: bridge
