apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game
spec:
  type: NodePort
  ports:
  - name: "game-service"
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: game
  
