apiVersion: v1
kind: Service
metadata:
  labels:
    app: ranking
  name: ranking
spec:
  type: NodePort
  ports:
  - name: "ranking-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: ranking
