apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game
  name: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - image: almuhs/gameapp:v2
        name: gameapp
        env:
                - name: MYSQL_HOST
                  value: db
        ports:
        - containerPort: 80
          name: gameapp
